/* Lychee-FD 页面统一配置 */

window.LYCHEE_CONFIG = {
  site: {
    title: "全双工大模型驱动的具身类人交互",
    subtitle: "Lychee-FD",
    slogan: "从轮流说话，到自然共话。",
    description: "让大模型在真实语音对话中同时倾听、理解、反馈与表达，并进一步驱动数字人和机器人形成自然交互闭环。",
    brand: "Lychee-FD",
    brandSub: "自然共话引擎",
  },

  navigation: [
    { label: "首页", target: "hero" },
    { label: "技术介绍", target: "technology" },
    { label: "评测效果", target: "results" },
    { label: "Demo 演示", target: "demo" },
    { label: "全双工驱动数字人", target: "embodied" },
  ],

  heroPills: ["自然打断", "实时反馈", "用户附和", "数字人驱动"],

  heroPromoVideo: {
    title: "Lychee-FD 交互演示",
    video: "assets/videos/xuanchuan.mp4",
    poster: "assets/images/demo/xuanchuan-poster.jpg",
    preload: "none",
    autoplay: false,
    muted: true,
    loop: false,
    playsinline: true,
  },

  metrics: [
    { value: "7.4%", label: "语音问答准确率提升", note: "语义准确保持" },
    { value: "28.5%", label: "打断与接话指标提升", note: "打断精确响应" },
    { value: "11.2%", label: "打断响应延迟降低", note: "反馈及时触达" },
    { value: "4.50", label: "语音自然度 UTMOS", note: "语音表达质量" },
  ],

  highlights: [
    {
      icon: "端",
      title: "原生端到端全双工架构",
      text: "摒弃冗余级联设计，统一文本、语音与控制通道，实现更高效的推理流程和更自然的对话体验。",
    },
    {
      icon: "分",
      title: "层次化语义-声学参数分离",
      text: "解耦深层语义建模与声学参数计算，缓解模态梯度冲突，兼顾推理效率与表征鲁棒性。",
    },
    {
      icon: "锚",
      title: "密集语义对齐通道",
      text: "引入帧级密集文本流作为显式语义锚点，对抗语义稀释，确保逻辑连贯与语义一致。",
    },
    {
      icon: "快",
      title: "实时推理加速",
      text: "适配多通道流式生成，结合 KV Cache 复用与上下文压缩，降低全双工交互延迟。",
    },
  ],

  imageAssets: {
    architectureCompare: {
      id: "architectureCompare",
      title: "三种语音大模型架构对比",
      src: "assets/images/architecture/architecture_compare.png",
      width: 1955,
      height: 924,
      type: "image",
      section: "Lychee-FD 架构",
      tags: ["架构对比", "参数分离"],
      enabled: true,
      description: "传统 Thinker-Talker 结构语义较稳但推理链路更重；完全共享的原生端到端结构效率高但容易模态干扰；Lychee-FD 通过浅层共享、深层分离取得平衡。",
    },
    fdArchitecture: {
      id: "fdArchitecture",
      title: "Lychee-FD 全双工模型架构",
      src: "assets/images/architecture/lychee_fd_architecture.svg",
      width: 1436,
      height: 807,
      type: "image",
      section: "方法架构",
      tags: ["主架构图", "三通道"],
      enabled: true,
      description: "模型在共享主干之后分出语义、声学和控制通道，分别承担内容理解、语音生成和交互控制。",
    },
    modalityConflict: {
      id: "modalityConflict",
      title: "模态冲突",
      src: "assets/images/paper/modality_layer_conflict.png",
      width: 1746,
      height: 1153,
      type: "image",
      section: "技术根因",
      tags: ["模态冲突", "参数分离"],
      enabled: true,
      description: "语音生成需要声学细节，语言理解需要稳定语义，两者在同一深层表示中容易互相干扰。",
    },
    semanticSparsity: {
      id: "semanticSparsity",
      title: "语义稀释",
      src: "assets/images/paper/semantic_layer_sparsity.png",
      width: 1745,
      height: 1452,
      type: "image",
      section: "技术根因",
      tags: ["语义稀释", "语义对齐"],
      enabled: true,
      description: "连续音频流中语义信号容易被声学帧稀释，导致长程逻辑、上下文和回复意图不稳定。",
    },
    resultRadar: {
      id: "resultRadar",
      title: "多维能力对比雷达图",
      src: "assets/images/charts/result_radar.png",
      width: 1993,
      height: 2151,
      type: "image",
      section: "评测效果",
      tags: ["雷达图", "能力对比"],
      enabled: true,
      description: "从问答准确率、打断响应、轮次响应、停顿识别、用户反馈识别等维度展示 Lychee-FD 的综合优势。",
    },
    utmosNaturalness: {
      id: "utmosNaturalness",
      title: "语音自然度对比",
      src: "assets/images/charts/utmos_naturalness.png",
      width: 2042,
      height: 1433,
      type: "image",
      section: "评测效果",
      tags: ["语音自然度", "UTMOS"],
      enabled: true,
      description: "在保持全双工交互能力的同时，维持稳定的语音表达质量。",
    },
    avatarStatic: {
      id: "avatarStatic",
      title: "数字人展示",
      src: "assets/images/avatar/avatar_static.png",
      width: 404,
      height: 412,
      type: "image",
      section: "数字人展示",
      tags: ["Demo of Digital Avatar", "数字人"],
      enabled: true,
      description: "Lychee-FD 驱动数字人形成自然语音、表情和口型联动。",
    },
    avatarSpeaking: {
      id: "avatarSpeaking",
      title: "数字人展示",
      src: "assets/images/avatar/avatar_speaking.png",
      width: 408,
      height: 412,
      type: "image",
      section: "数字人展示",
      tags: ["Demo of Digital Avatar", "说话状态"],
      enabled: true,
      description: "展示数字人在接收语音、生成短反馈与自然接话时的表情状态变化。",
    },
    shennieRobot: {
      id: "shennieRobot",
      title: "Shennie 机器人展示",
      src: "assets/images/avatar/shennie_robot.png",
      width: 931,
      height: 641,
      type: "image",
      section: "机器人展示",
      tags: ["Demo of Shennie Robot", "具身交互"],
      enabled: true,
      description: "Lychee-FD 可作为具身机器人背后的对话交互模块，驱动机器人实现自然打断、附和反馈和实时响应。",
    },
  },

  assetGroups: {
    architecture: ["architectureCompare", "fdArchitecture"],
    results: ["resultRadar", "utmosNaturalness"],
    embodied: ["avatarStatic", "avatarSpeaking", "shennieRobot"],
  },

  demoCases: [
    {
      id: "demo_user_backchannel",
      displayIndex: "02",
      category: "策略攻防",
      type: "discussion",
      title: "AI 产品策略攻防",
      subtitle: "围绕增长与留存展开多轮观点交锋，系统在高频打断中保持立场、追踪上下文并持续回应。",
      tags: ["高频打断", "观点攻防", "多轮追踪"],
      videoSources: ["assets/videos/demo-ai-product-comment.mp4"],
      poster: "assets/images/demo/demo02_v4.png",
      videoWidth: 1728,
      videoHeight: 1080,
      posterWidth: 960,
      posterHeight: 600,
      scene: "策略攻防",
      highlight: "即使用户不断反驳和插话，系统依然能够围绕核心议题持续推理，保持回应稳定。",
    },
    {
      id: "demo_user_strategy",
      displayIndex: "04",
      category: "策略辩论",
      type: "strategy",
      title: "增长与留存策略辩论",
      subtitle: "用户围绕新品是否应优先冲增长持续追问，系统在被打断后快速接回论点并保持观点连贯。",
      tags: ["快速接回", "上下文跟踪", "多轮辩论"],
      videoSources: ["assets/videos/demo-user-strategy.mp4"],
      poster: "assets/images/demo/demo04_v4.png",
      videoWidth: 1728,
      videoHeight: 1080,
      posterWidth: 960,
      posterHeight: 600,
      scene: "策略辩论",
      highlight: "在连续追问和观点攻防中，系统能够理解用户反驳重点，并围绕增长与留存持续展开分析。",
    },
    {
      id: "demo_cook_beef",
      displayIndex: "06",
      category: "厨房助手",
      type: "handsfree",
      title: "厨房实时烹饪助手",
      subtitle: "用户一边做饭一边追问下一步，系统结合当前食材和现场情况，快速给出可执行建议。",
      tags: ["免手交互", "实时追问", "即时修正"],
      videoSources: ["assets/videos/demo-cooking-beef.mp4"],
      poster: "assets/images/demo/demo06_v4.png",
      videoWidth: 1920,
      videoHeight: 1080,
      posterWidth: 960,
      posterHeight: 540,
      scene: "厨房助手",
      highlight: "在双手忙碌的厨房场景中，系统能够边听边答，持续辅助用户完成烹饪流程。",
    },

  ]
};
